services:
  leap-initiative:
    image: ekelejay/leap-initiative:latest
    container_name: leap-initiative
    ports:
      - "3001:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped